### ISSUE TITLE
zoom random crush...

### ISSUE THREAD

**Issue by phields** [leadedge/SpoutCam#4] opened 2020-09-19 14:38 UTC
When calling spoutcam in video conferencing software zoom, the zoom software will crash after a period of time and the screen output will be black.

**Comment by phields** [comment] 2020-09-19 15:25
[logs.zip](https://github.com/leadedge/SpoutCam/files/5250092/logs.zip)

**Comment by leadedge** [comment] 2020-09-20 06:14
I would have to reproduce this to trace it. Does it happen with both DirectX and OpenGL versions?

There are several applications where SpoutCam can give problems. Meanwhile there is a way around it using Spout and a webcam developed for OBS Studio.

https://spout.discourse.group/t/obs-studio-and-spoutcam/97

**Comment by phields** [comment] 2020-09-21 06:09
This issue only occurs in DX versions, re-enabling the virtual camera in DX versions will cause the zoom software to crash.
In some other software that needs to call the virtual camera, the DX version gets stuck after a while, and you can reproduce this problem in Discord.

**Comment by leadedge** [comment] 2020-09-21 14:37
OK that narrows it down. The fact that it takes a while suggests a leak of some kind.  Thanks very much for your interest and time. But I am sorry to say that, due to workload on other things at the moment, I can't predict when I will get up to looking at this.  Unfortunately the SpoutCam code is very old and has limits to what can be done. Generally I recommend using modern alternatives such as the plugin for OBS studio.

**Comment by leadedge** [comment] 2020-09-22 06:32
I have updated with the latest Spout code from the develop branch. I can get it working in Zoom and do not detect any memory leak and it does not crash. But Zoom lags from time to time and shows "Not responding", even with no Spout source. This clears itself after a while and could be caused by other factors. That's about all I can do at the present time.

**Comment by phields** [comment] 2020-09-22 06:56
Thanks for your time, I'll try testing on other video conferencing software to see if the screen stalling issue still exists.

**Comment by leadedge** [comment] 2020-09-23 08:45
I can confirm that OBS studio / VirtualCam works perfectly with Zoom.

There must be some problem with the DirectShow code itself but it's difficult to compare with the OBS Studio VirtualCam because it uses different methods.

I will try to trace it through. But meanwhile, thanks to [CatxFish](https://github.com/Fenrirthviti/obs-virtual-cam) there is very good solution for link between Spout and software like Zoom, MS Teams, Google Hangouts, Google meets etc. It's all Open source and easy to set up.

**Comment by leadedge** [comment] 2020-09-28 03:11
Please try the latest changes and let me know the result.

I do not find any crash, but that problem could still be there. Lag and freezing will still occur if 60fps is selected in SpoutCamSettings. An updated copy of this with a 30fps limit is on the Spout2 develop branch. Otherwise Zoom runs smoothly at 1920x1080 and 30fps.

Note that SpoutCam sets up resolution and fps when it starts and will not detect if the sender changes size or another one starts. Use the "Stop video/Start video" button to refresh with the new size/sender.

**Comment by phields** [comment] 2020-09-28 13:03
I test this on https://meeting.tencent.com/
About 4 minutes and 40 seconds after starting the SpoutCam, the screen sticks still, even there is no spout sender.

**Comment by leadedge** [comment] 2020-09-28 13:31
OK thanks for your reply.

Can you detect any memory increase that might indicate a leak? The fact that this occurs even without a sender is a good lead because there is no use of DirectX functions.

I am using a [Zoom meeting test](https://zoom.us/test) which only lasts a few minutes. The memory usage fluctuates but I can't see any overall increase over that time. I will test again, but I don't think that's the problem. I will examine the sequence of events once more.  What browser are you using?

Sorry but I can't read the text on the link you sent.

**Comment by phields** [comment] 2020-09-28 14:06
> OK thanks for your reply.
> 
> Can you detect any memory increase that might indicate a leak? The fact that this occurs even without a sender is a good lead because there is no use of DirectX functions.
> 
> I am using a [Zoom meeting test](https://zoom.us/test) which only lasts a few minutes. The memory usage fluctuates but I can't see any overall increase over that time. I will test again, but I don't think that's the problem. I will examine the sequence of events once more. What browser are you using?
> 
> Sorry but I can't read the text on the link you sent.
Sorry, you can check out this link, it's basically the same product.
https://voovmeeting.com/
I haven't found any obvious memory leaks, but the time to trigger a sticks is fixed.

**Comment by phields** [comment] 2020-09-29 02:03
[Uploading WeMeetDump.zip…]()

**Comment by phields** [comment] 2020-09-29 02:10
[WeMeetDump.zip](https://github.com/leadedge/SpoutCam/files/5295923/WeMeetDump.zip)
here is the dump file, hope it helps

**Comment by leadedge** [comment] 2020-09-29 02:31
I will go through these.
Meanwhile I have been able to reproduce the freeze using VoovMeeting. It's a slow process but I should be able to track it down. At this stage I suspect timing which has been a problem for Skype.

**Comment by leadedge** [comment] 2020-09-29 08:05
It think the latest version 2.015 will work OK, but it might not. So please let me know what you find. Thanks for the link to Voov Meeting. Without it I could not have traced this.

I found a problem in the timing section. It failed at some point and the sleep time calculated was excessive. Something was not returned properly but I could not unravel the methods used by the original author.

It's more complicated because VLC works fine with these methods, but with the simple timing it freezes. On the other hand, Zoom works with the simple method but not with the complicated one. I don't think it will be used with VLC anyway.

Also the problem of lag and freeze at 60 fps is resolved, so I will restore this option in SpoutCamSettings. Even so, it's best to select 30 fps for reduced CPU load unless you specifically need 60fps.

I tested it briefly with Resolume and Magic Music Visuals and it seems to be fine.

While I have this in mind, I will look a little further to find out why it doesn't show up in the camera list with MS Teams.

**Comment by leadedge** [comment] 2020-10-01 05:25
I am confident that SpoutCam is working well after extended testing with Voov Meeting. If there are any further problems I will look into them. I have created a release package which includes SpoutCamSettings. Also I discovered that MS Teams requires a webcam with audio, so SpoutCam is not compatible.

**Comment by leadedge** [comment] 2020-10-02 08:50
I have had VooV, Zoom and Skype all working at the same time at 1920x1080 for 2 hours with no problem. MS Teams requires a webcam with audio so that's not possible. Skype is mirrored and there does not seem to be any way to change it. VLC works OK as long as audio is disabled when selecting the DirectShow device. But red/blue are exchanged and it seems that this is a long standing bug so I will not pursue it any further.

I have improved speed significantly by using two staging textures for pixel download from the sender texture. I achieve 2.5 - 3.2 per frame compared to 8.5 - 10.2 previously. A source at 1920x1080 easily meets the frame time required for 30fps. I have updated source and binaries, and will update the release later. If you still find trouble with your environment I will keep investigating. Please let me know.

**Comment by leadedge** [comment] 2020-10-17 01:40
An extensive revision, Release 2.023, should finally resolve this issue.

The problem was limited to 32 bit software that does not support a DirectShow clock where TimeGetTime was used to get a time value. An incorrect multiplication/cast caused an overflow when time exceeded  the maximum for a 32 bit DWORD, 4294967295 or 0xFFFFFFFF. Therefore Voov Meeting froze at a repeatable time. In fact it was not frozen, but the Sleep interval for adjusting frame rate was excessive. The alternative timing method did not require TimeGetTime but was not as accurate. For MS Teams, the apparent audio problem was related to this.
Given that a repeatable fault has been found, I will close this issue now. Of course any further issues can be raised.

**Closed as completed by leadedge** 2020-10-17 01:40 UTC
